### PR TITLE
Allow spectrum-colorpicker to be an attribute

### PR DESCRIPTION
**Pull request by fernandopasik**
Solving issue
https://github.com/Jimdo/angular-spectrum-colorpicker/issues/26

### CODE REVIEW

**Comment by joscha** [comment]
Hi @fernandopasik - can you add a test for this please?

**Comment by fernandopasik** [comment]
@joscha I've added the test.

**Comment by joscha** [comment]
Nice, thank you!

**Comment by joscha** [comment]
Released as `1.4.1`.

**Comment by fernandopasik** [comment]
awesome!

**Pull request merged**
