### PR TITLE
Added objectEquality comparison to palette watch function

### PR DESCRIPTION
**Pull request by jvanhees**
Since the palette is an array, the watch function would not normally trigger. It requires an objectEquality comparison as described in the $scope.$watch function: https://docs.angularjs.org/api/ng/type/$rootScope.Scope

This would probably resolve issue #44 (https://github.com/Jimdo/angular-spectrum-colorpicker/issues/44).

### CODE REVIEW

**Comment by joscha** [comment]
can you add a test for this?

**Comment by jvanhees** [comment]
I searched through the unit tests, and it appears that there is already a test for this:
https://github.com/Jimdo/angular-spectrum-colorpicker/blob/master/test/unit/spectrumDirectiveSpec.js#L171

However, when I ran the Karma test using the karma verbose logger (https://github.com/usrz/javascript-karma-verbose-reporter), I noticed that that specific test is never run (it only runs the 'set' test), which explains why this was never an issue in the test:

Suites and tests results:

 - SpectrumDirective :
   * should be able to find the angular module : 3 ok
   - legacy :
     * should initialize spectrum when compiling the directive tag : 3 ok
     * should initialize spectrum when compiling the div tag with the directive atttribute : 3 ok
     * should update the model when changing the color in the colorpicker : 3 ok
     * should initialize the colorpicker with the correct default color : 3 ok
     * should use via the directive given options : 3 ok
     * should understand the disabled option : 3 ok
     * should destroy the spectrum picker when destroying the directive : 3 ok
     * **should set palette via evaluated value : 3 ok**
     * should cope with falsy color values : 3 ok
     * should reset the color to the fallback value, if provided : 3 ok
     * should return hex-values when format is set to hex : 3 ok
     * should return rgb-values when format is set to rgb via evaluated value : 3 ok
     * should return the same value if there is no format set : 3 ok
     - trigger handler :
       * should toggle the colorpicker, when the given trigger is clicked : 3 ok
       * should deregister the handler on directive destroy : 3 ok
   - eventing :
     * should propagate change to color on change : 3 ok
     * should not propagate change to color on change with update option set to false : 3 ok
     * should propagate change to color on show : 3 ok
     * should not propagate change to color on show with update option set to false : 3 ok
     * should propagate change to color on hide : 3 ok
     * should not propagate change to color on hide with update option set to false : 3 ok
     * should propagate change to color on move : 3 ok
     * should not propagate change to color on move with update option set to false : 3 ok
     * should correctly emit change event : 3 ok
     * should correctly emit show event : 3 ok
     * should correctly emit hide event : 3 ok
     * should correctly emit beforeShow event : 3 ok
     * should prevent opening if beforeShow returns false : 3 ok
     * should correctly emit move event : 3 ok

**Comment by jvanhees** [comment]
I've updated the unit test, the verbose logger now correctly displays the test and the number of test has increased to 31:

Suites and tests results:

 - SpectrumDirective :
   * should be able to find the angular module : 3 ok
   - legacy :
     * should initialize spectrum when compiling the directive tag : 3 ok
     * should initialize spectrum when compiling the div tag with the directive atttribute : 3 ok
     * should update the model when changing the color in the colorpicker : 3 ok
     * should initialize the colorpicker with the correct default color : 3 ok
     * should use via the directive given options : 3 ok
     * should understand the disabled option : 3 ok
     * should destroy the spectrum picker when destroying the directive : 3 ok
     * should set palette via evaluated value : 3 ok
     * **should update palette via evaluated value : 3 ok**
     * should cope with falsy color values : 3 ok
     * should reset the color to the fallback value, if provided : 3 ok
     * should return hex-values when format is set to hex : 3 ok
     * should return rgb-values when format is set to rgb via evaluated value : 3 ok
     * should return the same value if there is no format set : 3 ok
     - trigger handler :
       * should toggle the colorpicker, when the given trigger is clicked : 3 ok
       * should deregister the handler on directive destroy : 3 ok
   - eventing :
     * should propagate change to color on change : 3 ok
     * should not propagate change to color on change with update option set to false : 3 ok
     * should propagate change to color on show : 3 ok
     * should not propagate change to color on show with update option set to false : 3 ok
     * should propagate change to color on hide : 3 ok
     * should not propagate change to color on hide with update option set to false : 3 ok
     * should propagate change to color on move : 3 ok
     * should not propagate change to color on move with update option set to false : 3 ok
     * should correctly emit change event : 3 ok
     * should correctly emit show event : 3 ok
     * should correctly emit hide event : 3 ok
     * should correctly emit beforeShow event : 3 ok
     * should prevent opening if beforeShow returns false : 3 ok
     * should correctly emit move event : 3 ok

Browser results:

 - PhantomJS 1.9.8 (Mac OS X 0.0.0): 31 tests
   - 31 ok
 - Firefox 43.0.0 (Mac OS X 10.10.0): 31 tests
   - 31 ok
 - Chrome 47.0.2526 (Mac OS X 10.10.5): 31 tests
   - 31 ok

**Comment by Xiphe** [comment]
LGTM

**Comment by Xiphe** [comment]
i removed the changes to the `dist` files and merged this as 1a9583f60f6162e6547180c37c38b048e66e86e3 and 9c7c67dade5444ae13f66669938d9e384429e2da

**Comment by Xiphe** [comment]
released with [`v1.4.3`](https://github.com/Jimdo/angular-spectrum-colorpicker/tree/v1.4.3)

**Pull request closed without merging**
